x<-read.table("household_power_consumption.txt",header=TRUE,sep = ";")
x$date2<-as.Date(x$Date,"%d/%m/%Y")
x$time2<-strptime(x$Time,"%H:%M:%S")
x$weekday<-weekdays(x$date2,abbreviate=TRUE)
full <- paste(as.Date(x$Date,"%d/%m/%Y"), x$Time)
x$datetime <- as.POSIXct(full)

par(mfrow=c(2,2))
with(x, {
  plot(Global_active_power~datetime, type="l",ylab="Global Active Power (kilowatts)",xlab="")
  plot(Voltage~datetime, type="l",ylab="Voltage (volt)", xlab="datetime")
  plot(Sub_metering_1~datetime, type="l",ylab="Global Active Power (kilowatts)",xlab="")
  lines(Sub_metering_2~datetime,col='Red')
  lines(Sub_metering_3~datetime,col='Blue')
  legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, bty="n",legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
  plot(Global_reactive_power~datetime, type="l",ylab="Global Rective Power (kilowatts)",xlab="datetime")
})
dev.copy(png, file="plot4.png")
dev.off()
